""" 
CONFIGURATION FILE 
ROOT, PATH, SETTINGS, AND OTHER CONFIGURATION VARIABLES
"""

from pathlib import Path

#PROJECT ROOT 
PROJECT_ROOT = Path(__file__).parent.parent

#DATA PATHS
DATA_PATH = PROJECT_ROOT / "data"

PROCESSED_DATA_PATH = DATA_PATH / "processed"
RAW_DATA_PATH = DATA_PATH / "raw"


#OUTPUT FILE PATHS
CHUNKS_FILE_PATH = DATA_PATH / "ctxh_chunks.json"

#SOURCES FILE SETTINGS 
SUPPORTED_FILE_TYPES = [".md", ".txt"]

#EMBEDING SETTINGS
EMBEDDING_MODEL_NAME = "..."

